package com.enviouse.futureshops.server.escrow.checkpoint;

public enum EscrowPersistencePhase {
    CHECKPOINT_AFTER_TEMP_WRITE,
    CHECKPOINT_AFTER_TEMP_FORCE,
    CHECKPOINT_AFTER_GENERATION_MOVE,
    CHECKPOINT_AFTER_DIRECTORY_FORCE,
    JOURNAL_AFTER_TEMP_FORCE,
    JOURNAL_AFTER_GENERATION_MOVE,
    JOURNAL_AFTER_GENERATION_DIRECTORY_FORCE,
    JOURNAL_AFTER_POINTER_TEMP_FORCE,
    JOURNAL_AFTER_POINTER_MOVE,
    JOURNAL_AFTER_POINTER_DIRECTORY_FORCE,
    JOURNAL_BEFORE_CLEANUP,
    JOURNAL_AFTER_CLEANUP
}
