package com.enviouse.futureshops.server.escrow.audit;

public enum EscrowConservationViolationCode {
    ARITHMETIC_OVERFLOW,
    LEDGER_NOT_ZERO,
    LIABILITY_MISMATCH,
    CUSTODY_LOCAL_CORRUPTION,
    PROTECTED_MINT_LOCAL_CORRUPTION,
    PROTECTED_MINT_BATCH_DUPLICATED,
    PROTECTED_CUSTODY_BATCH_MISSING,
    PROTECTED_CUSTODY_DENOMINATION_MISMATCH,
    PROTECTED_CUSTODY_AUTHORIZATION_MISMATCH,
    PROTECTED_CUSTODY_SERVER_EVIDENCE_MISMATCH,
    PROTECTED_CUSTODY_CHECKSUM_MISMATCH,
    PROTECTED_CUSTODY_VALUE_MISMATCH,
    PROTECTED_CUSTODY_BATCH_DUPLICATED,
    PROTECTED_RESERVATION_QUANTITY_MISMATCH
}
