package com.enviouse.futureshops.server.market.profile;

public enum MarketProfileMutationResultCode {
    SUCCESS,
    NO_CHANGE,
    STALE_PROFILE,
    STALE_REPLAY_EPOCH,
    REQUEST_CONFLICT,
    REPLAY_UNAVAILABLE,
    MISSING_SESSION,
    STALE_ROUTE,
    WRONG_MODULE,
    WRONG_VIEW,
    SESSION_EXPIRED,
    RATE_LIMITED,
    PERMISSION_DENIED,
    MODULE_CONTROL_UNAVAILABLE,
    ESCROW_NOT_READY,
    MODULE_FROZEN,
    MODULE_DRAINING,
    MODULE_CANCEL_AND_REFUND,
    CLAIMS_ONLY,
    MODULE_DISABLED,
    VIEW_DISABLED,
    TARGET_NOT_FOUND,
    TARGET_CONFLICT,
    LIMIT_REACHED,
    SERVER_ERROR
}
